import Image from "next/image";import {Button} from "@/components/Button";import {SectionTitle} from "@/components/SectionTitle";import {Reveal} from "@/components/Reveal";import CinematicHero from "@/components/CinematicHero";import FeaturedDishes from "@/components/FeaturedDishes";import FlameStory from "@/components/FlameStory";import MenuHighlights from "@/components/MenuHighlights";import CateringShowcase from "@/components/CateringShowcase";import ReviewRail from "@/components/ReviewRail";import SharingSeal from "@/components/SharingSeal";import ArrowFillButton from "@/components/ui/arrow-fill-button";import {MapPin} from "lucide-react";import {getFeatured} from "@/lib/menu";
export default async function Home(){const featured=await getFeatured();return <>
 <CinematicHero/>
 <section className="px-5 py-28 md:px-10 md:py-40"><div className="mx-auto grid max-w-[1280px] items-center gap-16 md:grid-cols-2"><Reveal className="relative"><article className="group mx-auto max-w-[490px] rounded-[28px] bg-white p-3 shadow-2xl shadow-black/10 transition-transform duration-500 hover:-translate-y-2 md:p-4"><div className="relative aspect-[4/3] overflow-hidden rounded-[20px] bg-marble"><Image src="/images/storefront.png" alt="Greek Mansion counter and blue menu boards in Scarborough" fill className="object-cover transition-transform duration-700 ease-out group-hover:scale-[1.04]" sizes="500px"/></div></article><SharingSeal className="absolute -bottom-8 -right-3 hidden md:block"/></Reveal><Reveal><SectionTitle eyebrow="Our story" title="A taste of Greece"/><p className="mt-8 max-w-xl font-serif text-2xl leading-relaxed text-ink/75 md:text-3xl">Food has always been how we welcome people in. Around our table, recipes are remembered, stories are traded, and there is always room for one more.</p><p className="mt-7 max-w-lg text-sm leading-7 text-ink/60">We prepare the food we grew up with—bright lemon, fragrant oregano, honest ingredients and meat kissed by the open flame. Greek Mansion brings that familiar warmth to Scarborough, every day.</p><Button href="/about" variant="outline" className="mt-9">Our story</Button></Reveal></div></section>
 <section className="overflow-hidden bg-white px-0 py-28"><div className="mx-auto max-w-[1360px]"><Reveal className="px-5 md:px-10"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><SectionTitle eyebrow="House favourites" title="Featured dishes"/><p className="max-w-sm text-sm leading-7 text-ink/60">Drag through the dishes or use the arrows. Each favourite is rooted in Greek tradition and made for a generous table.</p></div></Reveal><div className="mt-8"><FeaturedDishes items={featured}/></div></div></section>
 <FlameStory/>
 <MenuHighlights items={featured}/>
 <CateringShowcase/>
 <section className="overflow-hidden bg-navy py-28 text-white"><Reveal className="px-5 md:px-10"><SectionTitle eyebrow="Kind words" title="From our guests" align="center" light/><p className="mx-auto mt-5 max-w-xl text-center text-sm leading-7 text-white/55">The kind of hospitality people remember—and generously share with others.</p></Reveal><div className="mt-10"><ReviewRail/></div><div className="mt-10 flex justify-center px-5"><div className="hidden sm:block"><ArrowFillButton btnText="Leave a Google Review" href="https://g.page/r/CWjzqGR7i7IAEBM/review" target="_blank" rel="noreferrer" aria-label="Leave Greek Mansion a review on Google" className="font-label shadow-xl shadow-black/20" bgColor="#F8F5ED" textColor="#1E2A78" fillBgColor="#C9A227" fillTextColor="#111936" hoverFillBgColor="#C9A227" hoverFillTextColor="#111936"/></div><Button href="https://g.page/r/CWjzqGR7i7IAEBM/review" target="_blank" variant="light" className="sm:hidden">Leave a Google Review</Button></div></section>
 <section className="bg-ink px-5 py-24 text-center text-white"><Reveal><MapPin className="mx-auto mb-6 text-gold"/><p className="eyebrow !text-white/50">Meet us in Scarborough</p><h2 className="display mx-auto mt-5 max-w-4xl text-5xl uppercase md:text-7xl">Your table is waiting</h2><p className="mt-6 text-sm leading-7 text-white/60">5651 Steeles Ave E #10<br/>Scarborough, Ontario</p><div className="mt-9 flex flex-wrap justify-center gap-3"><Button href="https://maps.google.com/?q=5651+Steeles+Ave+E+Scarborough+ON" variant="light">Get directions</Button><Button href="tel:+14162923333" variant="light">Call now</Button></div></Reveal></section>
 </>}
