"use client";

import {useEffect,useRef,useState} from "react";
const SCRIPT="/vendor/opentype.min.js",FONT="/fonts/greek-mansion-handwriting.ttf",EM=100;
type Geometry={full:string;contours:string[];x:number;y:number;w:number;h:number};
type Props={text:string;duration?:number;delay?:number;strokeWidth?:number;fill?:boolean;height?:string;className?:string};
let libPromise:Promise<any>|null=null;const fontCache=new Map<string,Promise<any>>();
function library(){if(typeof window==="undefined")return Promise.reject();const present=(window as any).opentype;if(present)return Promise.resolve(present);if(!libPromise)libPromise=new Promise((resolve,reject)=>{const script=document.createElement("script");script.src=SCRIPT;script.async=true;script.onload=()=>{const lib=(window as any).opentype;lib?resolve(lib):reject()};script.onerror=reject;document.head.appendChild(script)});return libPromise}
function font(url:string){let pending=fontCache.get(url);if(!pending){pending=Promise.all([library(),fetch(url).then(response=>{if(!response.ok)throw new Error("Font failed");return response.arrayBuffer()})]).then(([lib,buffer])=>lib.parse(buffer));fontCache.set(url,pending)}return pending}
export function HandwritingText({text,duration=1.5,delay=.05,strokeWidth=1.6,fill=true,height="1.15em",className=""}:Props){
 const root=useRef<HTMLSpanElement>(null),paths=useRef<(SVGPathElement|null)[]>([]);const [typeface,setTypeface]=useState<any>(null),[geom,setGeom]=useState<Geometry|null>(null),[lengths,setLengths]=useState<number[]>([]),[visible,setVisible]=useState(false),[drawn,setDrawn]=useState(false);
 useEffect(()=>{const node=root.current;if(!node)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){setVisible(true);observer.disconnect()}},{threshold:.35});observer.observe(node);return()=>observer.disconnect()},[]);
 useEffect(()=>{if(!visible)return;let cancelled=false;font(FONT).then(value=>{if(!cancelled)setTypeface(value)}).catch(()=>{});return()=>{cancelled=true}},[visible]);
 useEffect(()=>{if(!typeface||!text)return;const path=typeface.getPath(text,0,EM,EM),box=path.getBoundingBox(),pad=EM*.12,full=path.toPathData(2);setGeom({full,contours:full.split(/(?=M)/).filter((part:string)=>part.trim().length>1),x:box.x1-pad,y:box.y1-pad,w:box.x2-box.x1+pad*2,h:box.y2-box.y1+pad*2});setDrawn(false);setLengths([])},[typeface,text]);
 useEffect(()=>{if(!geom)return;setLengths(paths.current.slice(0,geom.contours.length).map(path=>path?path.getTotalLength():0));let second=0;const first=requestAnimationFrame(()=>{second=requestAnimationFrame(()=>setDrawn(true))});return()=>{cancelAnimationFrame(first);cancelAnimationFrame(second)}},[geom]);
 return <span ref={root} className="inline-block">{!geom?<span className={className}>{text}</span>:<svg viewBox={`${geom.x} ${geom.y} ${geom.w} ${geom.h}`} role="img" aria-label={text} className={`inline-block ${className}`} style={{height,width:`calc(${height} * ${(geom.w/geom.h).toFixed(4)})`,overflow:"visible"}}>{fill&&<path d={geom.full} fill="currentColor" style={{opacity:drawn?1:0,transition:drawn?`opacity .45s ease-out ${delay+duration*.72}s`:"none"}}/>}{geom.contours.map((d,index)=>{const length=lengths[index]||0,count=Math.max(1,geom.contours.length),each=duration/count*2.4,start=delay+index/count*duration;return <path key={index} ref={node=>{paths.current[index]=node}} d={d} fill="none" stroke="currentColor" strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" style={{strokeDasharray:length||1,strokeDashoffset:drawn?0:length||1,transition:drawn?`stroke-dashoffset ${each}s ease-out ${start}s`:"none"}}/>})}</svg>}</span>
}
